cfg = {}

cfg.eventuri = {
	--{"bank:deposit", "Money Inject (Banking)"},
	--{"bank:withdraw", "Money Inject (Banking)"},
	--{"bank:transfer", "Money Inject (Banking)"},
	--{"Banca:deposit", "Money Inject (Banking)"},
	--{"LegacyFuel:PayFuel", "Money Inject (Fuel)"},
	--{"lscustoms:payGarage", "Money Inject (LS Customs)"},
	{"dropOff", "Money Inject (vRP)"},
	{"PayForRepairNow", "Money Inject (vRP)"},
	--{"vrp_slotmachine:server:1", "Money Inject (Slot Machine)"},
	--{"vrp_slotmachine:server:2", "Money Inject (Slot Machine)"},
	--{"truckerJob:success", "Money Inject (Trucker)"},
	--{"paycheck:salary", "Money Inject (Paycheck)"},
	--{"paycheck:bonus", "Money Inject (Paycheck)"},
	{"esx_truckerjob:pay", "Money Inject (ESX)"},
	{"esx_pizza:pay", "Money Inject (ESX)"},
	{"esx_tankerjob:pay", "Money Inject (ESX)"},
	{"esx_vehicletrunk:giveDirty", "Money Inject (ESX)"},
	{"f0ba1292-b68d-4d95-8823-6230cdf282b6", "Money Inject"},
	{"gambling:spend", "Money Inject (ESX)"},
	{"265df2d8-421b-4727-b01d-b92fd6503f5e", "Money Inject (ESX)"},
	{"AdminMenu:giveDirtyMoney", "Money Inject (ESX)"},
	{"AdminMenu:giveBank", "Money Inject (ESX)"},
	{"AdminMenu:giveCash", "Money Inject (ESX)"},
	{"esx_slotmachine:sv:2", "Money Inject (ESX)"},
	{"esx_moneywash:deposit", "Money Inject (ESX)"},
	{"esx_moneywash:withdraw", "Money Inject (ESX)"},
	{"esx_moneywash:deposit", "Money Inject (ESX)"},
	{"mission:completed", "Money Inject (ESX)"},
	{"c65a46c5-5485-4404-bacf-06a106900258", "Money Inject (ESX)"},
	{"99kr-burglary:addMoney", "Money Inject (ESX)"},
	{"esx_jobs:caution", "Money Inject (ESX)"},
	{"esx_gopostaljob:pay", "Money Inject (ESX)"},
	{"esx_banksecurity:pay", "Money Inject (ESX)"},
	{"delivery:success", "Money Inject (ESX)"},
	{"taxi:success", "Money Inject (ESX)"},
	{"esx_pilot:success", "Money Inject (ESX)"},
	{"esx_taxijob:success", "Money Inject (ESX)"},
	{"esx_garbagejob:pay", "Money Inject (ESX)"},
	{"esx_garbagejob:pay", "Money Inject (ESX)"},
	{"esx_society:setJobSalary", "Money Inject (ESX)"},

	{"esx-qalle-jail:openJailMenu", "ESX Inject"},
	{"ambulancier:selfRespawn", "ESX Inject"},
	{"esx_ambulancejob:revive", "ESX Inject"},
	{"esx-qalle-jail:jailPlayer", "ESX Inject"},
	{"esx_jail:sendToJail", "ESX Inject"},
	{"esx_jailer:sendToJail", "ESX Inject"},
	{"esx_jailer:unjailTime", "ESX Inject"},
	{"JailUpdate", "ESX Inject"},
	{"UnJP", "ESX Inject"},
	{"js:jailuser", "ESX Inject"},
	{"fuel:pay", "ESX Inject"},
	{"esx:getSharedObject", "ESX Inject"},

	{"dmv:success", "vRP Inject"},
	{"RunCode:RunStringRemotelly", "vRP Inject"},
	{"RunCode:RunStringLocally", "vRP Inject"},

	{"mellotrainer:adminKick", "Mellotrainer"},
	{"mellotrainer:adminTempBan", "Mellotrainer"},
	{"mellotrainer:s_adminKill", "Mellotrainer"},
	{"mellotrainer:s_adminTp", "Mellotrainer"},
	{"mellotrainer:adminTime", "Mellotrainer"},
	{"mellotrainer:adminWind", "Mellotrainer"},
	{"mellotrainer:adminBlackout", "Mellotrainer"},
	{"mellotrainer:adminWeather", "Mellotrainer"},
	{"mellotrainer:isAdmin", "Mellotrainer"}
}

cfg.masini = {
    "menacer",
	"hydra",
	"buzzard",
	"deluxo",
	"avenger",
	"akula",
	"apc",
	"barrage",
	"caracara",
	"cargobob",
	"chernobog",
	"hunter",
	"insurgent",
	"starling",
	"lazer",
	"bombushka",
	"savage",
	"rhino",
	"khanjali",
	"oppressor",
	"oppressor2",
	"scramjet",
	"jet",
    "blimp",
    "blimp2",
    "blimp3",
	"cargoplane"
}

cfg.arme = {
    "WEAPON_PROXMINE",
	"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_RPG",
	"WEAPON_MINIGUN",
	"WEAPON_RAILGUN",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_GRENADE",
	"WEAPON_STICKYBOMB",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_RAYPISTOL",
	"WEAPON_RAYCARBINE",
	"WEAPON_RAYMINIGUN",
    "WEAPON_DIGISCANNER",
	"WEAPON_STINGER",
	"WEAPON_FIREWORK",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_GARBAGEBAG",
    "WEAPON_RAILPISTOL",
    "WEAPON_PISTOL_MK2",
    "WEAPON_SMG_MK2",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_SNSPISTOL_MK2",
    "WEAPON_REVOLVER_MK2",
    'WEAPON_SPECIALCARBINE_MK2',
    "WEAPON_BULLPUPRIFLE_MK2",
    "WEAPON_PUMPSHOTGUN_MK2",
    "WEAPON_MARKSMANRIFLE_MK2"
}

cfg.blcmd = {
    'FunCtionOk',
    'menu',
    'pk',
    'haha',
    'lol',  
    'xddd',
    'chocolate',
    'panickey',
    'jolmany',
    'killmenu'
}

cfg.obiecte = {
	"prop_gold_cont_01",
	"p_cablecar_s",
	"stt_prop_stunt_tube_l",
	"stt_prop_stunt_track_dwuturn",
	"p_spinning_anus_s",
	"prop_ld_ferris_wheel",
	"prop_ferris_car_01",
	"p_ferris_car_01",
	"stt_prop_ramp_spiral_l",
	"stt_prop_ramp_spiral_l_l",
	"stt_prop_ramp_multi_loop_rb",
	"stt_prop_ramp_spiral_l_xxl",
	"stt_prop_ramp_spiral_xxl",
	"stt_prop_stunt_bblock_huge_01",
	"stt_prop_stunt_bblock_huge_02",
	"stt_prop_stunt_bblock_huge_03",
	"stt_prop_stunt_bblock_huge_04",
	"stt_prop_stunt_bblock_huge_05",
	"stt_prop_stunt_bblock_hump_01",
	"stt_prop_stunt_bblock_qp",
	"stt_prop_stunt_bblock_qp2",
	"stt_prop_stunt_jump_loop",
	"stt_prop_stunt_landing_zone_01",
	"stt_prop_stunt_track_dwslope45",
	"stt_prop_stunt_track_dwturn",
	"stt_prop_stunt_track_dwslope30",
	"stt_prop_stunt_track_dwsh15",
	"stt_prop_stunt_track_dwshort",
	"stt_prop_stunt_track_dwslope15",
	"stt_prop_stunt_track_dwuturn",
	"stt_prop_stunt_track_exshort",
	"stt_prop_stunt_track_fork",
	"stt_prop_stunt_track_funlng",
	"stt_prop_stunt_track_funnel",
	"stt_prop_stunt_track_hill",
	"stt_prop_stunt_track_slope15",
	"stt_prop_stunt_track_slope30",
	"stt_prop_stunt_track_slope45"
}

cfg.plates = {
	"brutan",
	"brutan#7799",
	"gej",
	"lynxmenu",
	"eulencheats",
	"hamhaxia",
	"lynx",
	"bakarmenu",
	"fantamenumenu",
	"nahuel",
	"suca",
	"alphav",
	"fivemock"
}

return cfg